name: arturo sanchez
favicon: null
layout_spectrum: 0.26941
typography_spectrum: 0.32146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070101'
    - '#635144'
    - '#a19996'
    - '#d1b9a0'
  brandStrength: 0.8125
  lightness: 0.8746866676956415
  saturation: 0.6875
  rhythmicContrast: 0.1578096856828779
purpose: []
